# Generated by Django 3.2.8 on 2021-11-20 13:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
